version: "3"
services:
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: ./docker/mariadb/Dockerfile
    volumes:
      - "./docker/mariadb/data:/var/lib/mysql"
    ports:
      - "3308:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=react-nest
      - TZ=Asia/Tokyo
